### ISSUE TITLE
Plugin "entando-plugin-jpwtt" integration

### ISSUE THREAD

**Issue by christian1981** [entando/entando-components#17]
EntandoOldVersions repository contains "entando-plugin-jpwtt".
Is this component compatible with Entando's latest version and is there a road map for its integration?

Thx
Christian

**Comment by eugeniosant** [comment]
The wtt plug inserted into EntandoOldVersions project is not compatible with the current version of entando, and there are no plans to update it to the next version.

That being said, WTT is a simple plugin and it should not be difficult upgrade to the current version, and if you want contribute to the project, I propose to you to make a fork of the entando-components project and make a pull-request with the update of the component.
