### ISSUE TITLE
jpwebdynamicform - Error deleting a message with attributeRoles 

### ISSUE THREAD

**Issue by stefanopuddu** [entando/entando-components#2]
Deleting a `messageType` that contains `attributeRoles`, references are not properly handled.

```
DELETE on table 'JPWEBDYNAMICFORM_MESSAGES' caused a violation of foreign key constraint 'JPWEBDYNAMICFORM_ATTROLES_FKEY'
```

**Comment by eugeniosant** [comment]
Fixed by commit https://github.com/entando/entando-components/commit/ee087890a5de008d4fdf2284c91284d4e92281e6
