### ISSUE TITLE
jpphotogallery - Widget: Photo Gallery

### ISSUE THREAD

**Issue by VMtinapi** [entando/entando-components#5]
Add Filter doesn't work properly.

![schermata 2015-03-11 alle 10 32 46](https://cloud.githubusercontent.com/assets/11421387/6593565/05055dba-c7da-11e4-87d4-a5c7c05a8903.png)

**Comment by eugeniosant** [comment]
Fixed by commit https://github.com/entando/entando-components/commit/a14b75a397e3158eb3453d04740a5741fa8d59c1
