### ISSUE TITLE
JPmail Plugin

### ISSUE THREAD

**Issue by Aminshoshtaryzadeh** [entando/entando-components#518]
Hi, 
I have ask many time , but unfortunately there is no response from your company.
IS THERE ANY WAY TO RECEIVE MAIL WITH ATTACHMENT FROM NON REGISTERED USER IN ENTANDO PLATFORM version 5.0.1 or 5.1.0?
I would be appreciate if someone is reply.

**Comment by joewhite101** [comment]
Hi Amin,

You can certainly extend the JPMail plugin to do that. As you've seen the default implementation doesn't include attachments but you could easily add that logic. take a deeper look at the code in the package:
https://github.com/entando/entando-components/tree/master/plugins/entando-plugin-jpmail/src/main/java/com/agiletec/plugins/jpmail/aps/services/mail

And look at adding a new field for the attachment and adding it to the email you send. Fork the project or extend it inside of your Entando app and add what you need.

Also, this is our open source issue forum. If you need immediate support or have time sensitive issues I would recommend purchasing a support subscription from Entando. You can learn more about that at our commercial site: www.entando.com

**Comment by Aminshoshtaryzadeh** [comment]
thank you for your reply
